FROM node:lts-alpine as build-stage

WORKDIR /app

COPY . .

# ENV NODE_ENV=production
RUN npm install && npm run build


FROM nginx:stable-alpine as production-stage

RUN apk add --no-cache openssl bash

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./nginx-configs/* /etc/nginx/

RUN chmod +x /etc/nginx/configure_nginx.sh

# VOLUME /vol/static
VOLUME /vol/www

EXPOSE 80
EXPOSE 443

# CMD ["nginx", "-g", "daemon off;"]
CMD [ "/etc/nginx/configure_nginx.sh" ]
