FROM node:lts-alpine as develop-stage

WORKDIR /server

# RUN npm init -y && npm install mongodb express cors dotenv

ENV ATLAS_URI=mongodb+srv://Ardeshir:Ardoo8812@rw-cluster0.dbnjtu1.mongodb.net/?retryWrites=true&w=majority
ENV SPECKLE_TOKEN=cc88bd24757613820df460097dcf70085a8caa17c2
ENV PORT=5000
ENV DB_NAME=test_reconwood_2

CMD [ "bash" ]
