FROM node:lts-alpine as develop-stage

WORKDIR /server

COPY . .

RUN npm install

EXPOSE 5000

ENV ATLAS_URI=mongodb+srv://Ardeshir:Ardoo8812@rw-cluster0.dbnjtu1.mongodb.net/?retryWrites=true&w=majority
ENV PORT=5000
ENV DB_NAME=test_reconwood_2

ENV NODE_ENV=production

CMD [ "node", "server.mjs" ]
